### ISSUE TITLE
lwip/opt.h missing

### ISSUE THREAD

**Issue by bphermansson** [terenceang/esp8266-PIR#1]
I can't compile this software:

 make
CC modules/sntp.c
modules/sntp.c:45:22: fatal error: lwip/opt.h: No such file or directory
 #include "lwip/opt.h"
                      ^
What am I missing?

**Comment by terenceang** [comment]
You are missing some of the lwip headers the was not in the standard SDK. 
I used the headers from here https://github.com/kadamski/esp-lwip, merged into the SDK.

**Comment by bphermansson** [comment]
Seems to work, thanks!
